# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# List of Books

# Book.create(:title => 'Reading In Service Orientation (white papers)',:author =>'' ,:status => 'Available' ,:category => 'Interface Design' ,:copy => 1)
# Book.create(:title => 'Real Time UML',:author =>'Bruce Powel Douglass' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Writing Solid Code',:author =>'Steve Maguire' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Schaum\'s Data Structures',:author =>'Seymour Lipschutz' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Refactoring',:author =>'Martin Fowler' ,:status => 'Available' ,:category => 'Programming' ,:copy => 2)
# Book.create(:title => 'Head first Design Patterns',:author =>'Eric Freeman' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Being Geek',:author =>'Michael Lopp' ,:status => 'Available' ,:category => 'Software Requirement and Analysis' ,:copy => 1)
# Book.create(:title => 'Software Estimation',:author =>'Steve McConnell' ,:status => 'Available' ,:category => 'Software Requirement and Analysis' ,:copy => 1)
# Book.create(:title => 'Freakonomics',:author =>'Steven D Levitt' ,:status => 'Available' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'Python pocket reference',:author =>'Mark Lutz' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'C# in a Nutshell',:author =>'Joseph Albahari' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'HBR on Compensation',:author =>'' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'HBR on Talent Management',:author =>'' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'The Elements of Style',:author =>'' ,:status => 'Available' ,:category => 'Grammar' ,:copy => 1)
# Book.create(:title => 'Managing Humans',:author =>'' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'c# in Depth',:author =>'Jon Skeet' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'UML Distilled',:author =>'Martin Fowler' ,:status => 'Borrowed' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'The Rails 3 Way',:author =>'Obie Fernandez' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Essential .Net volume 1',:author =>'Don Box with Chris Sells' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Inside C#',:author =>'Tom Archer and Andrew Whitechapel' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Project Management',:author =>'' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'ASP.net MVC 3 Framework',:author =>'Adam Freeman' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'NHibernate in Action',:author =>' Pierre Henri Kuate' ,:status => 'Borrowed' ,:category => 'Programming	' ,:copy => 1)
# Book.create(:title => 'Don\'t Make Me Think',:author =>'Steve Krug' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'Programming WCF Services',:author =>'Juval Lowy' ,:status => 'Borrowed' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Patterns in Java',:author =>'Mark Grand' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Javascript for web development',:author =>'Nicholas C.Zakas' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Marketing 3.0',:author =>'Philip Kotler' ,:status => 'Available' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'ASP.Net 2.0',:author =>'Patrick A.Lorenz' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Drupal 6 Themes',:author =>'Ric Shrevas' ,:status => 'Available' ,:category => 'Interface Design' ,:copy => 1)
# Book.create(:title => 'Ajax Patterns',:author =>'Christian Gross' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => '.NET 1.1 Components',:author =>'Juval Lowy' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'The Radio Jockey Handbok',:author =>'Simran Kohli' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'Agile software Development',:author =>'Alistir Cockburn' ,:status => 'Available' ,:category => 'Software Requirement and Analysis' ,:copy => 1)
# Book.create(:title => 'High Performance MySQL',:author =>'Baron Schwartz' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Xtreme Programming explained',:author =>'Kent Beck' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Threads Primer',:author =>'Bil Lewis' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Xtreme Programming explored',:author =>'William C. Wake' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => '.NET Web Services',:author =>'Alex Ferrara' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'The Radio Jockey Handbok',:author =>'Simran Kohli' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'Stress that Motivates',:author =>'Dru Scott' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'One Minute Manager',:author =>'Ken Blanchard' ,:status => 'Available' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'The McKinsey Mind',:author =>'Ethan M. Rasiel' ,:status => 'Available' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'The McKinsey Way',:author =>'Ethan M. Rasiel' ,:status => 'Available' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'Working with difficult people',:author =>'Bobbi Linkemer' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'Windows Communication (WCF)',:author =>'' ,:status => 'Borrowed' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'The Mythical Man-Month',:author =>'Frederick P. Brooks,Jr.' ,:status => 'Available' ,:category => 'Software Requirement and Analysis' ,:copy => 1)
# Book.create(:title => 'The Five Dysfunctions of a team',:author =>'Patrick Lencioni' ,:status => 'Available' ,:category => 'Software Requirement and Analysis' ,:copy => 1)
# Book.create(:title => 'Steve Jobs - Comics',:author =>'' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'The Code Loader',:author =>'' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Reinventing you',:author =>'Dorie Clark' ,:status => 'Borrowed' ,:category => 'Management' ,:copy => 1)
# Book.create(:title => 'Agile Principles,Patterns, and Practices in C#',:author =>'Robert C. Martin' ,:status => 'Borrowed' ,:category => 'Programming	' ,:copy => 1)
# Book.create(:title => 'Head first Object oriented Analysis & Design',:author =>'Brett D. McLaughlin' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'Domain Driven Design',:author =>'Eric Evans' ,:status => 'Available' ,:category => 'Interface Design' ,:copy => 1)
# Book.create(:title => 'Patterns of Enterprise Application Architecture',:author =>'Martin Fowler' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'The Dilbert Principle',:author =>'Scott Adams' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'Developing Application Frameworks in .NET',:author =>'Xin Chen' ,:status => 'Available' ,:category => 'Programming' ,:copy => 1)
# Book.create(:title => 'A New Standard for Public and Private Health Insurance Enrollment',:author =>'' ,:status => 'Available' ,:category => 'Interface Design' ,:copy => 1)
# Book.create(:title => 'The Google Story',:author =>'' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'The Argumentative India',:author =>'Amartya Sen' ,:status => 'Available' ,:category => 'General' ,:copy => 1)
# Book.create(:title => 'Tipping Point',:author =>'Malcolm Gladwell' ,:status => 'Available' ,:category => 'General' ,:copy => 1)


# Quovantis Library Memebers

# Member.create!(:email => "hiren.sharma@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Hiren Sharma", :admin => false)
# Member.create!(:email => "dharmendra@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Dharmendra Singh", :admin => false)
# Member.create!(:email => "sudesh@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Sudesh Bainsla", :admin => false)
# Member.create!(:email => "nadisha.garg@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Nadisha Garg", :admin => true)
# Member.create!(:email => "subhash@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Subhash Kapoor", :admin => false)
# Member.create!(:email => "shalvika@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Shalvika Sood", :admin => false)
# Member.create!(:email => "vivek@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Vivek Rajan", :admin => false)
# Member.create!(:email => "richa@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Richa Bhardwaj", :admin => false)

# Member.create!(:email => "shanky.munjal@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Shanky Munjal", :admin => false)
# Member.create!(:email => "himanshu@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Himanshu Agrahari", :admin => false)
# Member.create!(:email => "sanjeev.kumar@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Sanjeev Kumar", :admin => false)
# Member.create!(:email => "divya@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Divya Dhuria", :admin => false)
# Member.create!(:email => "harsh.mittal@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Harsh Mittal", :admin => false)
# Member.create!(:email => "nitin.misra@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Nitin Misra", :admin => false)
# Member.create!(:email => "kundan.kumar@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Kundan Kumar", :admin => false)
# Member.create!(:email => "dilip.bhandari@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Dilip Bhandari", :admin => false)

# Member.create!(:email => "sunil@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Sunil Singh", :admin => false)
# Member.create!(:email => "priya.jain@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Priya Jain", :admin => false)
# Member.create!(:email => "abhishek@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Abhishek Kant", :admin => false)
# Member.create!(:email => "vaibhav.jain@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Vaibhav Jain", :admin => false)
# Member.create!(:email => "gautam.gupta@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Gautam Gupta", :admin => false)
# Member.create!(:email => "siddhant.bhardwaj@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Siddhant Bhardwaj", :admin => false)
# Member.create!(:email => "romit@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Romit Garg", :admin => false)
# Member.create!(:email => "vaishali.tanwar@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Vaishali Tanwar", :admin => false)

# Member.create!(:email => "pankhuri@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Pankhuri Kaushik", :admin => false)
# Member.create!(:email => "amit.gupta@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Amit Kumar Gupta", :admin => false)
# Member.create!(:email => "abhishek.shukla@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Abhishek Shukla", :admin => false)
# Member.create!(:email => "pushpraj.singh@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Pushpraj Singh", :admin => false)
# Member.create!(:email => "ashish@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Ashish kumar", :admin => false)
# Member.create!(:email => "surya.mishra@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Surya Mishra", :admin => false)
# Member.create!(:email => "shreya.goyal@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Shreya Goyal", :admin => false)
# Member.create!(:email => "ritika.arora@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Ritika Arora", :admin => false)

# Member.create!(:email => "anjani.singh@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Anjani Kumar ", :admin => false)
# Member.create!(:email => "amit.irodha@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Amit Irodha", :admin => false)
# Member.create!(:email => "dhiraj@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Dhiraj Saini", :admin => false)
# Member.create!(:email => "rajat.bansal@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Rajat Bansal", :admin => false)
# Member.create!(:email => "sunidhi@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Sunidhi Chatterjee", :admin => false)
# Member.create!(:email => "chetan.kohli@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Chetan Kohli", :admin => false)
# Member.create!(:email => "tarun@quovantis.com", :password => "Quovantis", :password_confirmation => "Quovantis", :name => "Tarun Kohli", :admin => false)

# IssueRecord.create!(:book_id => 12 ,:member_id=> 37 ,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 13 ,:member_id=> 37 ,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 15 ,:member_id=> 7 ,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 52 ,:member_id=> 7 ,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 55 ,:member_id=> 7 ,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 56 ,:member_id=> 6,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 21 ,:member_id=> 29 ,:due_date=>DateTime.strptime("28/06/2013", "%d/%m/%Y"))

# IssueRecord.create!(:book_id => 51 ,:member_id=> 21 ,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 25 ,:member_id=> 21,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 24 ,:member_id=> 21 ,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))

# IssueRecord.create!(:book_id => 23 ,:member_id=> 21,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))
# IssueRecord.create!(:book_id => 46 ,:member_id=> 15 ,:due_date=>DateTime.strptime("21/06/2013", "%d/%m/%Y"))